-- MySQL Script generated by MySQL Workbench
-- Wed May  5 16:33:20 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Webelweiss_CactusPic
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Webelweiss_CactusPic
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Webelweiss_CactusPic` DEFAULT CHARACTER SET utf8 ;
USE `Webelweiss_CactusPic` ;

-- -----------------------------------------------------
-- Table `Webelweiss_CactusPic`.`photographers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Webelweiss_CactusPic`.`photographers` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(320) NOT NULL,
  `passwordHash` VARCHAR(256) NOT NULL,
  `firstname` VARCHAR(50) NOT NULL,
  `lastname` VARCHAR(50) NOT NULL,
  `description` TEXT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `UniquePhotographer` (`email` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Webelweiss_CactusPic`.`photos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Webelweiss_CactusPic`.`photos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `imagePath` TINYTEXT NOT NULL,
  `imageHash` VARCHAR(64) NOT NULL,
  `name` VARCHAR(50) NOT NULL,
  `description` VARCHAR(2048) NULL,
  `takenDate` DATETIME NULL,
  `longitude` DECIMAL(10,8) NULL,
  `latitude` DECIMAL(10,8) NULL,
  `photographers_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_photos_photographers_idx` (`photographers_id` ASC) VISIBLE,
  UNIQUE INDEX `UniqueImage` (`imageHash` ASC) VISIBLE,
  CONSTRAINT `fk_photos_photographers`
    FOREIGN KEY (`photographers_id`)
    REFERENCES `Webelweiss_CactusPic`.`photographers` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
